CREATE TABLE IF NOT EXISTS procedures (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    steps JSONB NOT NULL DEFAULT '{}'::jsonb,
    outcome TEXT,
    warranty_status VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(120) NOT NULL,
    procedure_id INTEGER NOT NULL REFERENCES procedures(id) ON DELETE CASCADE,
    CONSTRAINT uq_tags_keyword_proc UNIQUE (keyword, procedure_id)
);

CREATE TABLE IF NOT EXISTS decision_nodes (
    id INTEGER PRIMARY KEY,
    procedure_id INTEGER NOT NULL REFERENCES procedures(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    yes_next INTEGER REFERENCES decision_nodes(id) ON DELETE SET NULL,
    no_next INTEGER REFERENCES decision_nodes(id) ON DELETE SET NULL,
    final_outcome JSONB
);

CREATE TABLE IF NOT EXISTS linked_nodes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    procedure_id INTEGER NOT NULL REFERENCES procedures(id) ON DELETE CASCADE,
    linked_procedure_id INTEGER NOT NULL REFERENCES procedures(id) ON DELETE CASCADE,
    CONSTRAINT uq_linked_nodes_pair UNIQUE (procedure_id, linked_procedure_id)
);

CREATE TABLE IF NOT EXISTS feedback_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    helpful BOOLEAN NOT NULL,
    procedure_id INTEGER REFERENCES procedures(id) ON DELETE SET NULL,
    query TEXT,
    branch_label VARCHAR(120),
    comment TEXT,
    outcome_diagnosis TEXT,
    feedback_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    triage_trace JSONB,
    final_decision_label VARCHAR(120),
    search_confidence DOUBLE PRECISION,
    search_confidence_state VARCHAR(40),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_procedures_category ON procedures(category);
CREATE INDEX IF NOT EXISTS idx_tags_keyword ON tags(keyword);
CREATE INDEX IF NOT EXISTS idx_tags_procedure_id ON tags(procedure_id);
CREATE INDEX IF NOT EXISTS idx_decision_nodes_procedure_id ON decision_nodes(procedure_id);
CREATE INDEX IF NOT EXISTS idx_linked_nodes_procedure_id ON linked_nodes(procedure_id);
CREATE INDEX IF NOT EXISTS idx_feedback_entries_created_at ON feedback_entries(created_at);
CREATE INDEX IF NOT EXISTS idx_feedback_entries_procedure_id ON feedback_entries(procedure_id);
